name: flutter_webrtc_demo
description: A new Flutter application.
version: 1.2.0

environment:
  sdk: ">=2.15.0 <3.0.0"
  flutter: ">=1.22.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.3
  flutter_webrtc: ^0.9.11
  shared_preferences: ^2.0.7
  http: ^0.13.3
  path_provider: ^2.0.2
  flutter_udid: ^2.0.1

  # Design pattern
  bloc: ^7.0.0
  flutter_bloc: ^7.0.0
  equatable: ^2.0.0
  firebase_dynamic_links: ^5.0.11
  firebase_core: ^2.4.1
  flutter_new_foreground_task: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
