// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmoSFP-H_aKugC3-GjgyimjqXUNwPQbS8',
    appId: '1:988951600645:web:cd9e06eed829a99f35066c',
    messagingSenderId: '988951600645',
    projectId: 'ttgo-development',
    authDomain: 'ttgo-development.firebaseapp.com',
    storageBucket: 'ttgo-development.appspot.com',
    measurementId: 'G-GSD0SM3X0C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZJwFpVnPdrOOyfYo1Penwi6eVDdmEvZs',
    appId: '1:988951600645:android:2bf6d2570eeb6cae35066c',
    messagingSenderId: '988951600645',
    projectId: 'ttgo-development',
    storageBucket: 'ttgo-development.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC151b8V5n0z7-dnPZVy7VwiWJGzISW0yc',
    appId: '1:988951600645:ios:84c92f9b3ea0cdf435066c',
    messagingSenderId: '988951600645',
    projectId: 'ttgo-development',
    storageBucket: 'ttgo-development.appspot.com',
    iosClientId: '988951600645-jqu7jb7rla9bd0a6b05ol7pquk3assui.apps.googleusercontent.com',
    iosBundleId: 'com.cloudwebrtc.flutterWebrtcDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC151b8V5n0z7-dnPZVy7VwiWJGzISW0yc',
    appId: '1:988951600645:ios:070e54df4898907835066c',
    messagingSenderId: '988951600645',
    projectId: 'ttgo-development',
    storageBucket: 'ttgo-development.appspot.com',
    iosClientId: '988951600645-rnnft8911i8vqg85mb5r3j4g5lqi9bk0.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterWebrtcDemo',
  );
}
